python run.py --config ./config/resnet50_All_Decision.yaml
python run.py --config ./config/resnet50_All_Feature.yaml
python run.py --config ./config/resnet50_All_INF.yaml
python run.py --config ./config/resnet50_All_Input.yaml
python run.py --config ./config/resnet50_All_SAR.yaml
python run.py --config ./config/resnet50_Armored_Decision.yaml
python run.py --config ./config/resnet50_Armored_Feature.yaml
python run.py --config ./config/resnet50_Armored_INF.yaml
python run.py --config ./config/resnet50_Armored_Input.yaml
python run.py --config ./config/resnet50_Armored_SAR.yaml
python run.py --config ./config/resnet50_Ground_Decision.yaml
python run.py --config ./config/resnet50_Ground_Feature.yaml
python run.py --config ./config/resnet50_Ground_INF.yaml
python run.py --config ./config/resnet50_Ground_Input.yaml
python run.py --config ./config/resnet50_Ground_SAR.yaml